filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: false
build:
    environment:
        php:
            version: 5.5
    tests:
        before:
            - 'phpunit'
